# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-vbguest", "vagrant-persistent-storage"]
  config.vm.box = "local/rocky-8"
  config.vm.define "vm" do |vm|
    vm.vm.network "private_network", ip: "192.168.99.11"  
  end
end
